#! /bin/bash

# VARIABLES

DIR=$(dirname "$0")
COLOR_FILE=$DIR/colors.png
COLOR_CODE=$DIR/colors.txt
CHAR="  "
#COLOR_FILE=256colors.png

if [ "$1" = "" ]
    then
    echo "Usage $0 file"
    exit 1
fi

source $DIR/colors.sh

# We need a tmp file to output the img data in txt format
FILE=$(mktemp XXXXXXX)
rm -f "$FILE"

convert "$1" -resize $(expr $(tput cols) "/" $(echo -n "$CHAR" | wc -c))\> +dither -remap $COLOR_FILE "$FILE.txt"
WIDTH=$(head -n1 "$FILE.txt" | sed -e 's/.* //g' -e 's/,.*//g')
#COLOR=$(cat  "$FILE.txt" | sed -e 's/^\#.*//g' -e 's/.* //g' -e 's/[^a-z].*//g' | tr '\n' ' ')
COLOR=$(cat "$FILE.txt" | sed -e '/^#/d' -e 's/^[^#]*#/v/g' -e 's/.*none/-/g' -e 's/ .*//g' | tr '\n' ' ')

rm -f "$FILE.txt"

# Display the img
W=0
TXT=
for C in $(echo $COLOR)
    #echo "$C:"
    do
        # Find color index 0..255
        if [ "$C" = "-" ]
        then
            # No color
            echo -e "\e[0m${CHAR}\c"
            #TXT="$TXT\e[0m${CHAR}"
        else
            eval "L=${!C}"
            echo -e "\e[48;05;${L}m${CHAR}\c"
        fi
    W=$(expr $W + 1)
    if [ $W -ge $WIDTH ]
        then
        # New line
        echo -e "\e[0m"
        #TXT="$TXT\e[0m\n"
        W=0
    fi
done
#echo -e "$TXT"
