#! /bin/bash

# VARIABLES

DIR=$(dirname "$0")
COLOR_FILE=$DIR/colors.png
COLOR_CODE=$DIR/colors.txt
CHAR="  "
#COLOR_FILE=256colors.png

WIDTH=""
QUIET=""
IMG=""
function help() {
  echo "Usage catimg [-qh] [-w width] [-c char] img"
  echo "By default char is \"  \" and w is the terminal width"
}

while getopts qw:c:h opt; do
  case "$opt" in
    q) QUIET="YES" ;;
    w) WIDTH="$OPTARG" ;;
    c) CHAR="$OPTARG" ;;
    h) help; exit ;;
    *) help ; exit 1;;
  esac
done

while [ "$1" ]; do
  IMG="$1"
  shift
done

if [ "$IMG" = "" -o ! -f "$IMG" ]; then
  help
  exit 1
fi

source $DIR/colors.sh

# We need a tmp file to output the img data in txt format
FILE=$(mktemp XXXXXXX)
rm -f "$FILE"

if [ ! "$WIDTH" ]; then
  COLS=$(expr $(tput cols) "/" $(echo -n "$CHAR" | wc -c))
  convert "$IMG" -resize $COLS\> +dither -remap $COLOR_FILE "$FILE.txt"
else
  COLS=$(expr $WIDTH "/" $(echo -n "$CHAR" | wc -c))
  convert "$IMG" -resize $COLS\> +dither -remap $COLOR_FILE "$FILE.txt"
fi
WIDTH=$(head -n1 "$FILE.txt" | sed -e 's/.* //g' -e 's/,.*//g')

#COLOR=$(cat  "$FILE.txt" | sed -e 's/^\#.*//g' -e 's/.* //g' -e 's/[^a-z].*//g' | tr '\n' ' ')
COLOR=$(cat "$FILE.txt" | sed -e '/^#/d' -e 's/^[^#]*#/v/g' -e 's/.*none/-/g' -e 's/ .*//g' | tr '\n' ' ')

rm -f "$FILE.txt"

# Display the img
W=0
TXT=""
for C in $(echo $COLOR)
    #echo "$C:"
    do
        # Find color index 0..255
        if [ "$C" = "-" ]
        then
            # No color
            if [ "$QUIET" ]; then
              TXT="$TXT\e[0m${CHAR}\c"
            else
              echo -e "\e[0m${CHAR}\c"
            fi
        else
            L="$(eval echo \$$C)"
            if [ "$QUIET" ]; then
              TXT="$TXT\e[48;05;${L}m${CHAR}\c"
            else
              echo -e "\e[48;05;${L}m${CHAR}\c"
            fi
        fi
    W=$(expr $W + 1)
    if [ $W -ge $WIDTH ]
        then
        # New line
        if [ "$QUIET" ]; then
          TXT="$TXT\e[0m\n"
        else
          echo -e "\e[0m"
        fi
        W=0
    fi
done
if [ "$QUIET" ]; then
  echo -e "$TXT"
fi
